#!/usr/bin/env python3
"""Aggregate one grand_benchmark.sh run directory into a single SUMMARY.md.

Reads maxmul_vs_kleidiai.csv (the machine-readable output of the layered
benchmark) plus the plain-text outputs of the other steps, and emits the
consolidated tables.  Numbers are median GFLOP/s unless stated otherwise.
"""
import csv
import os
import sys
from collections import defaultdict

OUT = sys.argv[1] if len(sys.argv) > 1 else "."
# Prefer the median-of-runs file when repeated runs were merged: between-run
# variance here is larger than the within-run sample spread, so a single run is
# not a reliable figure.
_AVG = os.path.join(OUT, "maxmul_vs_kleidiai_avg.csv")
CSV = _AVG if os.path.exists(_AVG) else os.path.join(OUT, "maxmul_vs_kleidiai.csv")
AVERAGED = os.path.exists(_AVG)

SQUARE = [(256, 256, 256), (512, 512, 512), (1024, 1024, 1024),
          (2048, 2048, 2048), (4096, 4096, 4096)]
LARGE_K = [(64, 8192, 512), (64, 16384, 512), (64, 32768, 512),
           (128, 8192, 512), (128, 16384, 512), (128, 32768, 512)]
SHAPES = SQUARE + LARGE_K
MM = ["SME 4x1", "SME 2x2", "SME 1x4", "SME 1x4sym", "SME 4x1ZP",
      "SME 1x4ZAIO", "SME 1x4Acc", "SME 1x4AccKc"]
SHORT = {"SME 4x1": "4x1", "SME 2x2": "2x2", "SME 1x4": "1x4",
         "SME 1x4sym": "1x4sym", "SME 4x1ZP": "4x1ZP", "SME 1x4ZAIO": "ZAIO",
         "SME 1x4Acc": "1x4Acc", "SME 1x4AccKc": "AccKc"}

rows = []
if os.path.exists(CSV):
    with open(CSV) as f:
        rows = list(csv.DictReader(f))


def get(exp, impl, M, K, N, field="gflops"):
    for r in rows:
        if (r["experiment"] == exp and r["implementation"] == impl
                and int(r["M"]) == M and int(r["K"]) == K and int(r["N"]) == N):
            try:
                return float(r[field])
            except ValueError:
                return None
    return None


def hot(impl, kc, field="gflops"):
    for r in rows:
        if (r["experiment"] == "hot_microkernel" and r["implementation"] == impl
                and int(r["K"]) == kc):
            try:
                return float(r[field])
            except ValueError:
                return None
    return None


def cell(v, fmt="{:.0f}"):
    return fmt.format(v) if v is not None else "-"


def read(name):
    p = os.path.join(OUT, name)
    return open(p).read() if os.path.exists(p) else ""


print(f"# Grand benchmark — {os.path.basename(os.path.abspath(OUT))}\n")
print("Single-thread FP32 GEMM on Apple M4. Median GFLOP/s unless noted.")
if AVERAGED:
    n = max((int(r.get("n_runs", 1)) for r in []), default=0)
    print("\n**Figures are the median across repeated full runs**, not a single run. "
          "This machine has no thread pinning available, and between-run variance "
          "is larger than the within-run sample spread: across the runs merged "
          "here the median row moves ~1%, but the worst rows move up to ~12%. "
          "Each row in the CSV carries its own `spread_pct` so any quoted number "
          "comes with its reliability. Differences below roughly 5% should not be "
          "read as real.")
print("Generated by `bench/grand_benchmark.sh`; raw outputs are alongside this file.\n")

env = read("environment.txt")
if env:
    print("## Environment\n\n```")
    print(env.rstrip())
    print("```\n")

n_rows = [r for r in rows if r.get("mode") != "zero_only"]
n_fail = sum(1 for r in n_rows if r.get("status") != "PASS")
if n_rows:
    print(f"**Correctness: {len(n_rows)} measured rows, {n_fail} failures.** "
          "Every implementation is checked against Accelerate `cblas_sgemm` plus "
          "FP64 dot products on sampled entries; the MaxMulSK overwrite kernels "
          "are additionally run on a sentinel-filled C so a missed overwrite "
          "cannot pass silently.\n")

# ---------------------------------------------------------------- hot
print("## 1. Hot micro-kernel — one C tile, panels resident\n")
print("Packing, output traversal and allocation all removed; the timed region is "
      "micro-kernel invocations only. `[amort]` amortises the ZA zero and the "
      "ZA->C store across the batch and has no KleidiAI counterpart, so it is a "
      "diagnostic, not a like-for-like number.\n")
cols = ["SME 4x1", "SME 2x2", "SME 1x4sym", "SME 1x4Acc",
        "SME 1x4Acc [amort]", "KAI 2VL", "KAI 8VS"]
names = ["4x1", "2x2", "1x4sym", "**1x4Acc**", "*1x4Acc amort*", "KleidiAI 2VL", "KleidiAI 8VS"]
print("| Kc | " + " | ".join(names) + " |")
print("|---:|" + "---:|" * len(names))
for kc in (128, 256, 512, 1024, 2048):
    print(f"| {kc} | " + " | ".join(cell(hot(c, kc)) for c in cols) + " |")
print()
print("ns per invocation:\n")
print("| Kc | " + " | ".join(names) + " |")
print("|---:|" + "---:|" * len(names))
for kc in (128, 256, 512, 1024, 2048):
    print(f"| {kc} | " + " | ".join(cell(hot(c, kc, "ns_per_invocation"), "{:.0f}")
                                    for c in cols) + " |")
print("\n*KleidiAI 8VS uses a 16x16 tile against everyone else's 1024-element "
      "tile, so it is not doing the same work per invocation.*\n")
print("> **Stability caveat for this experiment.** Across repeated runs the "
      "MaxMulSK rows and Accelerate reproduce to within +/-1.5%, but the "
      "KleidiAI rows in the hot-micro-kernel harness swing 5-9% (and KAI 8VS at "
      "Kc=128 by more than 70%). Its entry point does smstart/smstop per call, "
      "which this harness exercises far more often than any real GEMM does. "
      "Treat a 1x4Acc-vs-KleidiAI hot ratio near 1.0 as a tie, not a win; the "
      "end-to-end and prepacked rows below are stable for both sides.\n")

# ---------------------------------------------------------------- prepacked
print("## 2. Prepacked full GEMM — packing hoisted out of the timed region\n")
hdr = ["shape"] + [SHORT[m] for m in MM if m != "SME 1x4ZAIO"] + ["KleidiAI 2VL", "KleidiAI 8VS"]
print("| " + " | ".join(hdr) + " |")
print("|---|" + "---:|" * (len(hdr) - 1))
for (M, K, N) in SHAPES:
    r = [f"{M}x{K}x{N}"]
    for m in MM:
        if m == "SME 1x4ZAIO":
            continue
        r.append(cell(get("prepacked_full_gemm", m, M, K, N)))
    r.append(cell(get("prepacked_full_gemm", "KAI 2VL", M, K, N)))
    r.append(cell(get("prepacked_full_gemm", "KAI 8VS", M, K, N)))
    print("| " + " | ".join(r) + " |")
print()

# ---------------------------------------------------------------- end to end
print("## 3. End-to-end — unpacked A, B in; C out; packing timed\n")
hdr = (["shape"] + [SHORT[m] for m in MM]
       + ["KAI full-pack", "KAI panel", "Accelerate", "llama+KAI", "llama native"])
print("| " + " | ".join(hdr) + " |")
print("|---|" + "---:|" * (len(hdr) - 1))
for (M, K, N) in SHAPES:
    r = [f"{M}x{K}x{N}"]
    for m in MM:
        r.append(cell(get("end_to_end", m, M, K, N)))
    ko = get("end_to_end", "KAI 2VL", M, K, N)
    k8 = get("end_to_end", "KAI 8VS", M, K, N)
    kp = get("panel_blocked", "KAIpanel 2VL", M, K, N)
    kp8 = get("panel_blocked", "KAIpanel 8VS", M, K, N)
    r.append(cell(max([v for v in (ko, k8) if v is not None], default=None)))
    r.append(cell(max([v for v in (kp, kp8) if v is not None], default=None)))
    r.append(cell(get("end_to_end", "Accelerate", M, K, N)))
    r.append(cell(get("ggml_cpu", "llama-kleidiai", M, K, N)))
    r.append(cell(get("ggml_cpu", "llama-native", M, K, N)))
    print("| " + " | ".join(r) + " |")
print("\n`KAI full-pack` is KleidiAI's default flow (materialise both packed "
      "operands, then compute). `KAI panel` is the same kernel and the same "
      "packing routines driven by a MaxMulSK-style panel-blocked caller. "
      "`llama+KAI` pre-packs its weights at load time, which is excluded.\n")

# ---------------------------------------------------------------- packing cost
print("## 4. Packing cost — end-to-end minus prepacked\n")
print("| shape | 1x4sym | 1x4Acc | KleidiAI 2VL |")
print("|---|---:|---:|---:|")
for (M, K, N) in SHAPES:
    out = [f"{M}x{K}x{N}"]
    for impl in ("SME 1x4sym", "SME 1x4Acc", "KAI 2VL"):
        e = get("end_to_end", impl, M, K, N, "median_ms")
        p = get("prepacked_full_gemm", impl, M, K, N, "median_ms")
        out.append(f"{100 * (e - p) / e:.0f}%" if e and p and e > 0 else "-")
    print("| " + " | ".join(out) + " |")
print()

# ---------------------------------------------------------------- other outputs
for title, fname in (("5. Third-party baselines (NumPy / PyTorch)", "python_baselines.txt"),
                     ("6. Energy — average power, Joules and J/GFLOP", "energy.txt")):
    body = read(fname)
    if body.strip():
        print(f"## {title}\n\n```")
        print(body.rstrip())
        print("```\n")

bc = read("bench_compare.txt")
if bc.strip():
    print("## 7. bench_compare (the repo's original comparison table)\n\n```")
    print(bc.rstrip())
    print("```\n")
